name: Codecov
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'
          channel: 'stable'

      # Get dependencies
      - name: Install dependencies
        run: dart pub get

      # Run all tests with coverage
      - name: Run tests with coverage
        run: dart run test --coverage="coverage"

      # Convert to LCOV
      - name: Convert coverage to LCOV
        run: dart run coverage:format_coverage --lcov --in=coverage --out=coverage.lcov --packages=.dart_tool/package_config.json --report-on=lib

      # Upload coverage data
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: buijs-dev/kradle
          file: coverage.lcov
